describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://innovation.kapiva.in/')
    
    cy.get('#home button.border-gray-300').click();
    cy.get('#root button.bg-white').click();
    cy.get('#root button.bg-transparent').click();
    cy.get('#root input[type="email"]').click();
    cy.get('#root input[type="email"]').type('sampleuser1@example.com');
    cy.get('#root input[type="password"]').click();
    cy.get('#root input[type="password"]').type('password123');
    cy.get('#root button.w-full').click();
    cy.get('#root button.text-white').click();
    cy.get('#root input[placeholder="Enter your full name"]').click();
    cy.get('#root input[placeholder="Enter your full name"]').type('Testing Anjali2');
    cy.get('#root input[placeholder="Enter your mobile number"]').click();
    cy.get('#root input[placeholder="Enter your mobile number"]').type('9876543210');
    cy.get('#root input[placeholder="Enter your country"]').click();
    cy.get('#root input[placeholder="Enter your country"]').click();
    cy.get('#root input[placeholder="Enter your country"]').type('India');
    cy.get('#root input[placeholder="Enter your city"]').click();
    cy.get('#root input[placeholder="Enter your city"]').type('Bangalore');
    cy.get('#root button.border-\\[\\#A8AF88\\] span.hidden').click();
    cy.get('#root button.w-full span').click();
    cy.get('#root select.w-full').select('startup');
    cy.get('#root input[placeholder="Enter your organisation"]').click();
    cy.get('#root input[placeholder="Enter your organisation"]').click();
    cy.get('#root input[placeholder="Enter your organisation"]').type('Tech Solutions Inc');
    cy.get('#root input[placeholder="e.g., 5 members, 3 core + 2 advisors"]').click();
    cy.get('#root input[placeholder="e.g., 5 members, 3 core + 2 advisors"]').type('5 members');
    cy.get('#root textarea[rows="5"]').click();
    cy.get('#root textarea[rows="5"]').type('Anjali - Lead, John - Researcher');
    cy.get('#root textarea[rows="3"]').click();
    cy.get('#root textarea[rows="3"]').click();
    cy.get('#root textarea[rows="3"]').type('Previous research in wellness tech');
    cy.get('#root button.border-\\[\\#A8AF88\\] span.hidden').click();
    cy.get('#root svg.lucide-arrow-right').click();
    cy.get('#root input[placeholder="Enter your project title"]').click();
    cy.get('#root input[placeholder="Enter your project title"]').type('AI Wellness Tracker');
    cy.get('#root input[placeholder="A brief one-liner about your project"]').click();
    cy.get('#root input[placeholder="A brief one-liner about your project"]').type('Tracking health via AI');
    cy.get('#root div:nth-child(4) select.w-full').select('formulations');
    cy.get('#root div:nth-child(5) select.w-full').select('early');
    cy.get('#root button.border-\\[\\#A8AF88\\] span.hidden').click();
    cy.get('#root button.w-full').click();
    cy.get('#root textarea[rows="6"]').click();
    cy.get('#root textarea[rows="6"]').type('Improved health outcomes.');
    cy.get('#root textarea[placeholder="Describe the problem and its significance..."]').click();
    cy.get('#root textarea[placeholder="Describe the problem and its significance..."]').type('Urban population 25-45.');
    cy.get('#root textarea[placeholder="Explain what sets your project apart..."]').click();
    cy.get('#root textarea[placeholder="Explain what sets your project apart..."]').type('Global wellness market.');
    cy.get('#root button.border-\\[\\#A8AF88\\] span.hidden').click();
    cy.get('#root button.w-full').click();
    cy.get('#root textarea[placeholder="What outcomes do you expect if this project succeeds?"]').click();
    cy.get('#root textarea[placeholder="What outcomes do you expect if this project succeeds?"]').type('Improved health outcomes.');
    cy.get('#root textarea[placeholder="Describe your target beneficiaries..."]').click();
    cy.get('#root textarea[placeholder="Describe your target beneficiaries..."]').type('Urban population 25-45.');
    cy.get('#root textarea[placeholder="Describe the market opportunity and how your solution can scale..."]').click();
    cy.get('#root textarea[placeholder="Describe the market opportunity and how your solution can scale..."]').type('Global wellness market.');
    cy.get('#root button.border-\\[\\#A8AF88\\] span.hidden').click();
    cy.get('#root button.w-full').click();
    cy.get('#root input[placeholder="e.g., ₹50,00,000"]').click();
    cy.get('#root input[placeholder="e.g., ₹50,00,000"]').type('₹10,00,000');
    cy.get('#root input[placeholder="e.g., 18 months"]').click();
    cy.get('#root input[placeholder="e.g., 18 months"]').type('12 months');
    cy.get('#root textarea[placeholder="List the major milestones and deliverables..."]').click();
    cy.get('#root textarea[placeholder="List the major milestones and deliverables..."]').type('M1: Prototype, M2: Testing');
    cy.get('#root textarea[placeholder="Provide a high-level budget breakdown..."]').click();
    cy.get('#root textarea[placeholder="Provide a high-level budget breakdown..."]').type('R&D: 50%, Marketing: 50%');
    cy.get('#root button.border-\\[\\#A8AF88\\] span.hidden').click();
    cy.get('#root button.w-full span').click();
    cy.get('#root svg.lucide-upload').click();
    cy.get('#proposal-upload').click();
    cy.get('#root div.flex-col.items-center.gap-3').click();
    cy.get('#proposal-upload').click();
    cy.get('#root svg.lucide-upload').click();
    cy.get('#proposal-upload').click();
    cy.get('#root a.hover\\:underline').click();
    cy.get('#root svg.w-10 path[d="M10 9H8"]').click();
    cy.get('#supporting-upload').click();
    cy.get('#root button.border-\\[\\#A8AF88\\] span.hidden').click();
    cy.get('#root button.w-full span').click();
    cy.get('#root div:nth-child(1) > div.flex > button.text-\\[\\#506000\\]').click();
    cy.get('#root input[placeholder="A brief one-liner about your project"]').click();
    cy.get('#root button.border-\\[\\#A8AF88\\]').click();
    cy.get('#root button.w-full').click();
    cy.get('#root svg.lucide-arrow-right').click();
    cy.get('#root button.w-full').click();
    cy.get('#root button.w-full span').click();
    cy.get('#root svg.lucide-arrow-right').click();
    cy.get('#root label:nth-child(1) input.rounded').check();
    cy.get('#root label:nth-child(2)').click();
    cy.get('#root label:nth-child(2) input.rounded').check();
    cy.get('#root button.w-full').click();
    cy.get('#root button.w-full').click();
    cy.get('#root button.hover\\:bg-\\[\\#506000\\]\\/5 span.hidden').click();
    cy.get('#root div.space-y-4 > div:nth-child(1) > div.justify-between > a.flex').click();
    cy.get('#root div.space-y-2 a.flex').click();
    cy.get('#root button:nth-child(4)').click();
    cy.get('#contact [name="name"]').click();
    cy.get('#contact [name="name"]').click();
    cy.get('#contact [name="name"]').type('Testing Anjali2');
    cy.get('#contact [name="email"]').click();
    cy.get('#contact [name="email"]').type('sampleuser1@example.com');
    cy.get('#contact [name="message"]').click();
    cy.get('#contact [name="message"]').type('Testing');
    cy.get('#contact button.flex').click();
    cy.get('#root nav.hidden button:nth-child(3)').click();
    cy.get('#root button:nth-child(4)').click();
    cy.get('#root a.text-white').click();
    cy.get('#contact p.text-gray-700').click();
    cy.get('#contact p.text-gray-700').click();
    cy.get('#contact p.text-gray-700').click();
    cy.get('#contact').click();
    cy.get('#contact span.underline').click();
    cy.get('#root button.gap-1\\.5 span.text-xs').click();
    cy.get('#root a.border').click();
    cy.get('#root svg.lucide-user').click();
    cy.get('#root button:nth-child(2) span.text-sm').click();
    cy.get('#root button.w-full span').click();
    cy.get('#root button.border-gray-300 span.hidden').click();
    cy.get('#root div.justify-center').click();
    cy.get('#root button:nth-child(3) span.text-sm').click();
    
  })
})